### ISSUE TITLE
Add possibility to retest only selected page from the suite

### ISSUE THREAD

**Issue by rzasap** [Cognifide/aet#113]
Sometimes there is a need to retest only particular page. For example, there was some environment/browser glitch and we want to retest that page without running the whole suite.

Ideally there should be some button in the report which will trigger that.

![image](https://cloud.githubusercontent.com/assets/18657753/26439544/f1132484-4128-11e7-940b-f9e28964e166.png)

**Comment by Skejven** [comment]
This is addressed in #337 - lets move the discussion there.
