### ISSUE TITLE
Issue with site width

### ISSUE THREAD

**Issue by GrzegorzBednarski** [Cognifide/aet#118]
I want to test site with width 1920px. I run aet tests (2.1.0 prod) and i have 1904px on my aet results (-16px).
I tried to add 33 px for firefox scroll, so i used 1953px width - aet results : 1937px (-16px)

Code snippet:
...

 <collect>
                        <resolution width="1920" height="1080"/>
                        <open/>
                        <wait-for-page-loaded/>
                        <screen name="Desktop Wide"/>

                        <resolution width="1024" height="768"/>
                        <open/>
                        <wait-for-page-loaded/>
                        <screen name="Desktop"/>
...

**Comment by tomekmwagner** [comment]
Hi Grzegorz,
we'll look closer on this issue and will get back to you.
Thanks,
Tomek

**Comment by tkaik** [comment]
After talking with @GrzegorzBednarski I'm closing this issue because it's not occurring anymore on AET 3.0.0+ (with Chrome browser)
