### ISSUE TITLE
Update Click Modifier with find elements by css selector

### ISSUE THREAD

**Issue by Skejven** [Cognifide/aet#14]
Update Click Modifier and add possibility to find element to hide by `cssSelector`.
Finding elements by xpath should be still possible, example:

``` xml
<collect>
  ...
  <click css="#learnMore" timeout="3000"/>
  <click xpath="//*[@id='about-anim']" timeout="3000"/>
  ...
</collect>
```

As part of this task, extend `integration-tests` with case where click by css selector will be used.
Update proper page in the documentation.

**Comment by subiron** [comment]
done as part of https://github.com/Cognifide/aet/pull/41
