### ISSUE TITLE
Cannot compare source code after switching to TLS 1.2 only

### ISSUE THREAD

**Issue by karoldrazek** [Cognifide/aet#140]
It seems that after disabling anything different than TLS 1.2 we're getting following errors on source code comparison tab:

Processing error occurred!
Details:

["Step: `source` (with parameters: {}) thrown an exception when collecting url: /en-us/aet/analytics/product-detail-page in: `cp-zg-extension-aet-test-sample` test. Cause: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake"]

**Comment by Skejven** [comment]
Fixed
