### ISSUE TITLE
advanced install instructions - JDK 7 from Oracle?

### ISSUE THREAD

**Issue by warn4n** [Cognifide/aet#148]
Documentation: The advanced install instructions in the wiki say Java 7 from Oracle. However Java 7 no longer seems to be available for Linux or Windows from Oracle. Can the instructions be updated to allow OpenJDK? Or will that not work?

**Comment by Skejven** [comment]
Thanks for the question.
OpenJDK should work, as this is default JDK for AET Vagrant instance now.
Oracle JDK 7 is still available, but you need to sign in to get it.

I've updated wiki: https://github.com/Cognifide/aet/wiki/LinuxAndWindowsSetup#linux-setup
