### ISSUE TITLE
Update Hide Modifier with find elements by css selector

### ISSUE THREAD

**Issue by Skejven** [Cognifide/aet#15]
Update Hide Modifier and add possibility to find element to hide by `cssSelector`.
Finding elements by xpath should be still possible, example:

``` xml
<collect>
  ...
  <hide css="#learnMore"/>
  <hide xpath="//*[@id='about-anim']" />
  ...
</collect>
```

As part of this task, extend `integration-tests` with case where hiding by css selector will be used.
Update proper page in the documentation.

**Comment by subiron** [comment]
done as part of https://github.com/Cognifide/aet/pull/41
