### ISSUE TITLE
Ambiguous message presented when test name contain /

### ISSUE THREAD

**Issue by PiotrRybickiCognifide** [Cognifide/aet#165]
The message presented by Maven Client that runned suite with Test containing / in the name doesn't say the reason correctly:

> [ERROR] ... Failed to process test suite: Not Found -> [Help 1]

Message should be:
>[ERROR] At least one of the Tests in the suite contain unsupported character. Please check and rename tests containing special characters.<

**Comment by mchrominski** [comment]
Currently, after the changes in #183 the message looks like:
`[ERROR] Failed to schedule test suite: '[Status: 400] Something is wrong with your suite definition! Value 'first/test' of attribute name in test does not match pattern `[a-zA-Z\-_0-9]+`!'`

I believe this is self-exploratory now so closing this issue.
