### ISSUE TITLE
[Request] Docker support?

### ISSUE THREAD

**Issue by testingplusme** [Cognifide/aet#235]
Hey Guys,
AET's very interesting project and idea. Do you think about support docker and create docker image for it?
Cheers,
Michał

**Comment by Skejven** [comment]
Hi @testingplusme 
Currently we decided to use Vagrant which another way to automate AET environment setup.
If you wish to setup AET using any known cloud provider (like AWS or Digitalocean) you might be interested in https://github.com/Cognifide/aet-cookbook repository, where AET Chef cookbooks are open-sourced.
To setup a local environment, please try [AET Vagrant](https://github.com/Cognifide/aet/tree/master/vagrant#vagrant) which is a part of the AET codebase.
Let us know if you have any further questions or comments.

**Comment by testingplusme** [comment]
@Skejven Thank for your reply :)
I tried to do it on my server but something it's wrong with CentOS .
![image](https://user-images.githubusercontent.com/17097924/37652809-abce6dd2-2c34-11e8-9440-c511541411ec.png)
Ofc, I installed all of vagrant needed plugins. Do you know what it's wrong?
Cheers!

**Comment by Skejven** [comment]
@testingplusme any update on that problems?

**Comment by testingplusme** [comment]
@Skejven sorry  I forgot to reply. Yep, it's ok. Thanks for your help!

**Comment by Skejven** [comment]
Good to hear, closing this question.

**Comment by arustamov** [comment]
I bet docker would be such a welcomed feature here but looks like not plan so far(

**Comment by Skejven** [comment]
@testingplusme , @arustamov there is Docker support for AET (but it is not official **yet**). 
Please look at my repository: https://github.com/Skejven/aet-docker I've created Docker images and example configuration for docker swarm that runs entire AET cluster.

**Comment by testingplusme** [comment]
Awesome. Great!
