### ISSUE TITLE
Let's not have version number in filenames of jars for Karaf

### ISSUE THREAD

**Issue by wiiitek** [Cognifide/aet#248]
### Version used

* `AET 2.1.6`

### Context of the issue/feature

Currently our bundles final name (filename) consist of groupID, artifactId and version (and extension of course). This might be problematic because when we want to deploy new version over the old during development process we need to delete old files. I mean:

1. Someone set-up AET instance with Vagrant
2. The last released versions of bundles are used for this setup (i.e. `2.1.6`)
3. Then some development is done
4. And Maven is used to upload new version of bundles: `mvn clean install -Pupload`

*Actual:*
Bundles are uploaded, but the old ones still are there. Karaf shows both versions as active

*Expected:*
New versions should *update* the bundles that are on Karaf.

For Karaf we could have bundles with following filenames:

```
${groupId}.${artifactId}.jar
```

If we haven't version in filename then new files would just overwrite old ones.

For Maven the version in Maven artifact is probably still required. So we need to adjust configuration for:

1. development lifecycle (wagon plugin that uploads bundles to Karaf)
2. release lifecycle (*zip* module that creates release packages)

### Appendix

In future this would allow us to further simplify development and deployment process.

**Comment by Skejven** [comment]
Fixed in #281
