### ISSUE TITLE
Ambiguous message when client times out 

### ISSUE THREAD

**Issue by Skejven** [Cognifide/aet#284]
### Version used

* `AET 2.1.6`

### Context of the issue/feature

When AET Maven Client times out (parameter [`timeout`](https://github.com/Cognifide/aet/wiki/ClientApplication#parameters) is exceeded, that means no update was received from the AET Server for that period of time) ambigous message is presented to the end user:
`[ERROR] Failed to process test suite: 'sleep interrupted'`

### Steps to reproduce

1. Run any suite with very short `timeout` parameter set, e.g. `mvn aet:run -Dtimeout:1`
Result:
Message `[ERROR] Failed to process test suite: 'sleep interrupted'` presented in console
Expected:
More meaningful message is presented, e.g.:
`[ERROR] Failed to process test suite: 'Suite processing request was timed out after ${timeout-param-value} ms of waiting for feedback from AET server. This could mean that AET instance is heavy loaded or is temporary unavailable. Please try again in few minutes.`

**Comment by Slasheruus** [comment]
I'm not able to reproduce it. My error was attached
![myerror](https://user-images.githubusercontent.com/41109829/44031954-e77fe902-9f05-11e8-9ad6-26fde5a434a0.PNG)
