### ISSUE TITLE
Keyboard shortcuts for 'Accept/Revert url/test' buttons

### ISSUE THREAD

**Issue by dlewandowski-cognifide** [Cognifide/aet#317]
### Version used

* `AET 2.1.6`

### Context of the issue/feature

There are buttons for accepting/reverting collected patterns in AET reporting App (check attached screens), but it is inconvenient to use them while navigating with keybaord shortcuts bettween different reports, because the user has to click them using mouse cursor. 

***The aim of this task is*** to provide dedicated keyboard shortcuts for accept/revert buttons.

***Solution proposition:***
Introduce following keyboard shortcuts:
***A*** - for accepting suite/test/url
***R*** - for reverting suite/test/url
***ctrl*** - modifier that will define that the specific opened test case should be accepted/reverted (***ctrl + A*** - accepts opened test case ; ***ctrl + R*** - reverts opened test case )

**Comment by sp2mbn** [comment]
Ctrl+A and Ctrl+R are not proper shortcuts, because are natively used in browsers. IMHO Shift key will be better as a modifier.

**Comment by kaczymuczy** [comment]
If someone tries to enter "R" into the filter input then the shortcut will execute or not?

**Comment by sp2mbn** [comment]
I think it shouldn't, but existing shortcuts (e.q. "q" or "e") are executed. If it's not wanted behavior that all existing shortcuts should be fixed.
