### ISSUE TITLE
Improve tooltip message layout for notes

### ISSUE THREAD

**Issue by jedrzejosinski** [Cognifide/aet#32]
Whenever a user move over a "add note" button, a tooltip is dispalyed.
Currently there is a message "Click to update this ... note" with some empty space left above which does not look well:
![2016-11-18_11h56_53](https://cloud.githubusercontent.com/assets/23552542/20427840/30d60c26-ad86-11e6-985c-6c719ebe4f8b.png)
The purpose of that one-line-space is to separate a tip from the actual note if it is added:
![2016-11-18_11h22_02](https://cloud.githubusercontent.com/assets/23552542/20427791/fc6b789a-ad85-11e6-8991-d9029dbec43f.png)
Let's try to improve the UX. A suggested solution is to remove that empty space and simply make a tip message visually different than a note, e.g. use two different font colors, bold vs. italic, sizes, etc.

**Comment by Skejven** [comment]
Fixed in #229
