### ISSUE TITLE
Support for comparing patterns between suites

### ISSUE THREAD

**Issue by mmajchrzak** [Cognifide/aet#35]
It would be very useful to be able to compare gathered snapshots with patterns from other suites. Use case:
1. I have two environments: staging and prod
2. I want to deploy a code to staging, run AET and eventually accept all new changes as new patterns
3. I want to deploy the same code to prod, run AET and automatically compare snapshots with these new patterns from staging. Thanks to this, I don't need to review and accept changes on prod manually.

The mechanism would need to take into consideration obvious differences between environments, like different domains, etc

**Comment by Skejven** [comment]
The scenario described above is already possible when using AET.
You may run the same suite first at staging with [domain parameter](https://github.com/Cognifide/aet/wiki/ClientApplication#parameters) set e.g. to `-Ddomain=http://staging.domain.com` and then you may run it again on prod (the same suite) with `-Ddomain=http://domain.com`. Doing so, first run on staging will establish patterns that will be compared with results during the run on prod domain.

**Comment by Skejven** [comment]
New functionality from #106 should make described process a lot easier now.
