### ISSUE TITLE
report popup window unification

### ISSUE THREAD

**Issue by RdkLwg** [Cognifide/aet#367]
### Version used

* `AET 3.0.`

### Context of the issue/feature

It looks like every single report pop-up window differs from one another a bit:
* the history popup looks completely different from the shortcuts or note editor popup windows
* the shortcuts "X" icon (to close the window) on the history window differs from the "X" icon on the history window while it is not available on the note-editor window.

For details see the image attached in the Appendix section.

### Appendix

![shortcuts](https://user-images.githubusercontent.com/22235601/46014109-84496a80-c0ce-11e8-8253-b92fba8e4e95.png)

![note-editor](https://user-images.githubusercontent.com/22235601/46014121-8c090f00-c0ce-11e8-83ef-27e57d6a5066.png)

![aet-history](https://user-images.githubusercontent.com/22235601/46014133-94f9e080-c0ce-11e8-8317-a4afb68bedb8.png)

**Comment by mchrominski** [comment]
I would also align the wording in the popup - the third line with "use" verb seems bit odd in the context of all the "press"es
