### ISSUE TITLE
Show full source when there has been no difference discovered

### ISSUE THREAD

**Issue by RdkLwg** [Cognifide/aet#369]
### Version used

* `AET 3.0`

### Context of the issue/feature

When I go to the `Source tab` and there are no issues found by the tool
And I click the `Show Full Source` button
The source code is not shown.

The source should be shown as if there were some changes discovered.

### Steps to reproduce

1. Open your report
2. Find some test with source tested but without changes discovered 
3. Go to the Source tab
4. Click the 'Show Full Source' button
5. Note that the source is not shown

### Appendix

![show-source](https://user-images.githubusercontent.com/22235601/46074859-0e560980-c189-11e8-9580-6161e2eeea96.png)

**Comment by RdkLwg** [comment]
Note that the other issue related to showing the source has been raised at #370.

**Comment by tkaik** [comment]
Fixed in https://github.com/Cognifide/aet/pull/413
