### ISSUE TITLE
End of the URL is cut off

### ISSUE THREAD

**Issue by rogemus** [Cognifide/aet#37]
When URL is to long is just cut off. There should be  `...` or some other indicator when URL is to long.

(at the end should be: `/grid960-12.html`)
![image_from_skype](https://cloud.githubusercontent.com/assets/9271549/20770136/efd01d7a-b744-11e6-92ff-4c0f07b66c84.png)
.

**Comment by wiiitek** [comment]
Thank you @rogemus !
It would be nice to have those `...` in the middle of URL.
Or the URL could be wrapped...
Do you have some other ideas of such indicator?

**Comment by rogemus** [comment]
I think we can use this white space next to URL, decrease font size by 2/3 px, and add scrollbar or wrap text when URL is to long

**Comment by Skejven** [comment]
This is already fixed.
