### ISSUE TITLE
Improper 'View source' url

### ISSUE THREAD

**Issue by RdkLwg** [Cognifide/aet#370]
### Version used

* `AET 3.0`

### Context of the issue/feature

When the user clicks the 'View source' url that has been generated for a given page she/he is redirected to a regular page (not its source).

### Steps to reproduce

1. Open your report
2. Go to the Source tab
3. Click the link generated under 'View source'
4. Note that the instead of showing the source of the page the regular page opens

### Appendix
![view-source](https://user-images.githubusercontent.com/22235601/46075521-faaba280-c18a-11e8-8973-16ec2f7047c7.png)

**Comment by RdkLwg** [comment]
Note that the other issue related to showing the shource has been raised at #369.

**Comment by tkaik** [comment]
Fixed in https://github.com/Cognifide/aet/pull/409/
