### ISSUE TITLE
Missing tooltip for the cases that passed conditionally (left nav panel)

### ISSUE THREAD

**Issue by RdkLwg** [Cognifide/aet#375]
### Version used

* `AET 3.0`

### Context of the issue/feature

When I mouseover test cases that passed conditionally in the left nav panel there is no tooltip informing me that this is the number of "Conditionally passed cases" as it is in case of the main panel (top bar with metadata). In fact there is the "Passed tests" tooltip only.

### Steps to reproduce

1. Open any report
2. Mouseover statistics in the left nav panel
3. Note that there are tooltips for each group of test cases but for those that passed conditionally

### Appendix

For details see the screenshot below:

![2018-09-26_16h11_34](https://user-images.githubusercontent.com/22235601/46085747-00af7c80-c1a7-11e8-82fc-ca9326e72b65.png)

As you can see in the screenshot there is no tooltip for "Conditionally passed cases". There is only one common tooltip for "Passed tests" and "Conditionaly passed cases".

**Comment by RdkLwg** [comment]
The feature seems to work properly in R3.2

**Comment by Necromantian** [comment]
Cannot reproduce, probably fixed.

**Comment by annabudziszewska** [comment]
Tested and accepted
version: 3.3.1.SNAPSHOT
