### ISSUE TITLE
New scroll page modifier

### ISSUE THREAD

**Issue by ernestosiak** [Cognifide/aet#386]
### Version used

* `AET 3.0.1`

### Context of the issue/feature

As a AET user I want to be able to scroll page to top / bottom / specific place. Now only available option is to use [Execute JavaScript Modifier](https://github.com/Cognifide/aet/wiki/ExecuteJavaScriptModifier) and custom script.

Only three attributes should be available: 
- `position`  with value `"top"` or `"bottom"`
- `css`
- `xpath`

If none is provided, default would be `position="bottom"`

Possible usage examples:
`<scroll position="top"/>`
`<scroll position="bottom"/>`
`<scroll css="#element_id"/>`
`<scroll xpath="//*[@id='element_id']"/>`

**Comment by tkaik** [comment]
Done in https://github.com/Cognifide/aet/pull/394
