### ISSUE TITLE
UI bug - no horizontal scrolling on js error pages

### ISSUE THREAD

**Issue by GrzegorzBednarski** [Cognifide/aet#393]
### Version used

* `AET 3.0.1`

### Context of the issue

I noticed that I'm not able to use horizontal scroll on pages with code errors (js errors, status codes, accessibility).

### Steps to reproduce

1. Open report with long js error (can be status code error or any other backend error report page)
2. You will see that we are not able to scroll horizontally.

Link to internal report site provided to Tomasz Kaik from AET dev team.

**Comment by tkaik** [comment]
Fixed in https://github.com/Cognifide/aet/pull/396
