### ISSUE TITLE
Conditionally passed tests - possibility to accept test case

### ISSUE THREAD

**Issue by ernestosiak** [Cognifide/aet#400]
### Version used

* `AET 3.0.1`

### Context of the issue/feature

As a AET user I would like to be able to accept test case (replace pattern) for tests that passed conditionally (like in any other failed rebaseable test result)

### Steps to reproduce

1. Setup simple layout test that will pass conditionally
2. There is no button to accept test

### Screenshot
![feature-conditional-test](https://user-images.githubusercontent.com/44050749/47081497-11ce3500-d20b-11e8-8769-0ad1a5947b1b.gif)

**Comment by tkaik** [comment]
Fixed in https://github.com/Cognifide/aet/pull/403
