### ISSUE TITLE
Ambiguous message presented when URLs are duplicated or empty

### ISSUE THREAD

**Issue by artswie** [Cognifide/aet#436]
If in single suite will exist empty or duplicated URLs (this might happen fairly easy on huge suites) you will get ambiguous messages while running "malformed" xml. 

The message presented on jenkins on older version of aet (2.1.3):
`[ERROR] Failed to process test suite: 'Not Found'`

The message presented on jenkins on lastest version of aet (3.1.0):
`[ERROR] Failed to schedule test suite: '[Status: 400] Bad Request`

Please provide ERROR message which will be more informative OR prevent it in some other way. 

Please run below code and unncomenty one of urls to see a failure.
```
<?xml version="1.0" encoding="UTF-8"?>
<suite name="testing" company="cognifide" project="cog" domain="https://www.cognifide.com">
  <test name="Accessibility" useProxy="rest">
    <collect>
	  <resolution width="1920"/>
      <open/>  
	  <accessibility standard="WCAG2AAA" />  
    </collect>
    <compare>
      <accessibility report-level="ERROR" />
    </compare>
	<urls>		
		<url href="/contact-us"/>
		<!--<url href=""/>-->
		<!--<url href="/contact-us"/>-->
	</urls>
	</test>
</suite>
```

Cheers!

**Comment by radoslawkarwacki** [comment]
I looked into it and made a little improvement (will create pull request shortly). 

The logs for this set of URLs:

    <urls>      
        <url href=""/>
        <url href="/test0"/>
        <url href="/test0"/>
        <url href="/test1" name="name-1"/>
        <url href="/test1" name="name-1"/>
        <url href="/test2" name="name-2"/>
        <url href="/test2" name="name-3"/>
        <url href="/test3" description="description-1"/>
        <url href="/test3" description="description-1"/>
        <url href="/test4" description="description-2"/>
        <url href="/test4" description="description-3"/>
    </urls>

Will be:

```
[Status: 400] Something is wrong with your suite definition! Detected errors: 
Empty url
Duplicated url, with URL: /test0, with name: /test0
Duplicated url, with URL: /test1, with name: name-1
Duplicated url, with URL: /test3, with name: /test3, with description: description-1
Duplicated url, with URL: /test4, with name: /test4, with description: description-3

Ideally, this should also contain line numbers. I didn't dig deep into it, but I'm not sure if the Simple XML Framework library can provide them. That should be considered as another improvement.

Also, please note that currently, entries with the same href and different names are not treated as a duplicate. I'm not a frequent AET user, so I'm not sure if the name serves some other important purpose, but if not, then the logic should probably be changed to treat every entry with identical href as a duplicate.

**Comment by annabudziszewska** [comment]
Tested and accepted
version: 3.3.1.SNAPSHOT
