### ISSUE TITLE
XML attribute values in suite.xml are not un-escaped

### ISSUE THREAD

**Issue by tkaik** [Cognifide/aet#441]
**Describe the bug**
When the suite XML file contains attributes with escaped special characters (e.g. `&` escaped to `&amp;` in url's `href` attribute), AET does not un-escape such value. Therefore it forces us to write unescaped special characters in suite file to achieve expected behaviour, which makes them invalid XML.

* Version used: `AET 3.1.0`

**To Reproduce**
1. Prepare a suite.xml file with url's href attribute with multiple query string parameters (to use `&` sign), e.g. `<url href="https://en.wikipedia.org/wiki/Main_Page?a=b&amp;c=d"/>` (you may modify example suite from https://github.com/Cognifide/aet/wiki/AETIn10Minutes#set-up-the-test )
2. Run the suite (e.g. `./aet.sh http://localhost:8181 suite.xml`)
3. Open the report and navigate to the example URL with query parameters
4. See that the URL is displayed with `&amp;` - it should have been un-escaped to `&` by AET. Also if you click on the URL displayed in the report, it takes you to the page with `&amp;` in query string.

**Expected behavior**
AET should un-escape all escaped XML characters in the suite xml. I would also recommend that AET should only accept suite XML files which are valid XML files.

**Screenshots**
![2018-11-27_11h11_18](https://user-images.githubusercontent.com/8331703/49074694-86968500-f235-11e8-973f-7123fc686c5b.png)

**Additional context**

**Comment by jdalkowski** [comment]
I came across the same problem and stack with not possibility to test url containing ampersand `&`   but I found a temporary workaround for this issue, maybe help someone too:

You can use `domain`suite attribute to pass character that should be un-escaped during test run, so for example when you want to test url 
`http://example.com/something/?pageId=12345&restofurladdress#tab=data` 

You could put beginning of url into suite attribute:
```domain="http://example.com/something/?pageId=12345&amp;"```

And then in the `url` modifier pass the rest of the tested url:
```<url href="restofurladdress#tab=data" /> ```

**Comment by dzuma** [comment]
This was done within https://github.com/Cognifide/aet/pull/524
I think this task can be closed.

**Comment by annabudziszewska** [comment]
Tested and accepted
