### ISSUE TITLE
Note after re-run doesn't exist.

### ISSUE THREAD

**Issue by Slasheruus** [Cognifide/aet#443]
There are 4 levels of notes. 
1(suite level) - it works properly. 
2(test level)  - it works properly. 
3(url level)  - it works properly. 
4(case level)  - after re-run the note disappears.
* Version used: 3.1.0

**To Reproduce**
1.Add note on each level.
2. Save the changes
3.Re-run the same suite and open the newest report.
4. There are no note on the level  4

**Expected behavior**
There are note on the level 4

**Comment by Skejven** [comment]
There is one more level - `case level` which was not working properly and fixed in #363 .

**Comment by wblachowski** [comment]
Can't reproduce this bug with AET 3.2.0 and changes from PR #363.

**Comment by RdkLwg** [comment]
The issue still exists in the version 3.2.2.

**Comment by Cich0sza** [comment]
Can't reproduce this bug in the current version of AET. Maybe it's related with specific suite configuration.

**Comment by RdkLwg** [comment]
Looks like the issue no longer exists.

**Comment by annabudziszewska** [comment]
Tested and accepted
Separate issue concerning notes has been reported: https://github.com/Cognifide/aet/issues/584
