### ISSUE TITLE
Entire codesniffer JS source file is written to logs for each accessibility collect

### ISSUE THREAD

**Issue by tkaik** [Cognifide/aet#446]
**Describe the bug**
When using the accessibility collector in a suite, the entire  codesniffer JS source file is written to logs for each accessibility collection. This happens only in the DEBUG logs level - however this should not happen even on this level - this JS file contains few thousands lines of code.

CC @plutasnyy 

* Version used: `AET 3.1.0`

**To Reproduce**
0. Make sure that the Logger on your AET environement (karaf) is set to DEBUG mode
1. Prepare a suite XML with a test using accessibility collector.
2. Run the suite
3. View the `worker.log` file - see the entry starting with
`<time> | DEBUG | com.cognifide.aet.jobs   | JavaScriptJobExecutor              51 | Executing JavaScript command: /*` followed by the whole source of [htmlcs.js file](https://github.com/Cognifide/aet/blob/master/core/jobs/src/main/resources/collectors/accessibility/htmlcs.js)

**Expected behavior**
Option 1 - When writing the JS code snippet to the log file, it's length should be limited to some reasonable value (e.g. first 100 characters). 
Option 2 -The Accessibility collector should not log the content of executed JS file at all

**Comment by Skejven** [comment]
We had already short chat about that with @plutasnyy 
My suggestion is to:
1) Change log level in [`JavaScriptJobExecutor.executeJs`](https://github.com/Cognifide/aet/blob/master/core/jobs/src/main/java/com/cognifide/aet/job/common/utils/javascript/JavaScriptJobExecutor.java#L50) to `TRACE` (trace is a good level to log such details).
2) Add separate `DEBUG` level logs in every collector/modifier that calls `JavaScriptJobExecutor.executeJs` that will say something like:
> Executing MODIFIER_NAME ...
