### ISSUE TITLE
ESXI or Hyper-V

### ISSUE THREAD

**Issue by SebaM** [Cognifide/aet#45]
Hey are you gonna support ESXI or Hyper-V in near future? I would need to migrate VM from VirtualBox to some other virtualization server. And I'm thinking also about calling eat:run remotely. Is it possible at all?

**Comment by Skejven** [comment]
Hello @SebaM, thank you for your question.
If you are asking about ESXi/Hyper-V in the context of Vagrant - we don't have plans in the near future to support it. However, we are currently working on Vagrant that runs AET in advanced configuration (Windows and Linux).
The good news is that you can already use [AET cookbook](https://github.com/Cognifide/aet-cookbook) with a Linux machine which is run by Hyper-V/ESXi.
Please have in mind that Vagrant and cookbook are just a convenient way to run AET but not the only one. You can always set it up manually.
Let us know if you have further questions or require support.
