### ISSUE TITLE
Test various Mobile device and browser

### ISSUE THREAD

**Issue by tuan91** [Cognifide/aet#471]
Hi, is it possible to test various mobile devices  and browser?
If so, how can I do that?
Thank you!

**Comment by wblachowski** [comment]
Hello @tuan91. As you can read in the project's readme, AET is not meant to be a cross-browser testing tool. 
When it comes to mobile testing, you can use [ResolutionModifier](https://github.com/Cognifide/aet/wiki/ResolutionModifier) and provide resolution of the device you are intrested in.
