### ISSUE TITLE
AET version in the report

### ISSUE THREAD

**Issue by RdkLwg** [Cognifide/aet#475]
When I need to check the version of AET I am using at the moment I cannot do it easily. I would like to get this possibility in the report.

Below the ? icon with shortcuts there can be a new i (like information) added. After clicking this the user will see a pop-up window like in case of shortcuts with some basic information like:
* Generated with AET {version-number}
* If you have any questions or require technical support please contact us at aet@cognifide.com. Gitter Chat is a way for users to chat with the AET community. Feel free to leave a message, even if we’re not around, we will definitely respond to you when available.

+ AET and Cognifide logo and the year the current version has been released in.

**Comment by hotowy** [comment]
I start working on this issue on forked repository.

**Comment by tkaik** [comment]
Fixed in https://github.com/Cognifide/aet/pull/506
