### ISSUE TITLE
Add tooltip for the re-run button in Report

### ISSUE THREAD

**Issue by RdkLwg** [Cognifide/aet#476]
The user can re-run the suite from the report by using a dedicated button.
However, unlike all the other useful elements in the report, it has no tooltip configured.

The button should be provided with some proper tooltip text according to the item it refers, so that the user could find out what its function is e.g.:
- re-run suite,
- re-run test,
- re-run URL.

**Comment by wblachowski** [comment]
Unless I'm mistaking them for something else, those tooltips are already present. There are even screenshots depicting them in PR #412.

![aettooltips](https://user-images.githubusercontent.com/20361302/52126178-e68f1a80-262e-11e9-96f3-905e1eede14d.png)

**Comment by RdkLwg** [comment]
Just checked and I cannot see them in Chrome (Version 72.0.3626.81 (Official Build) (64-bit) although I can see tooltips related to _localizing the currently opened ur_l and _clicking to navigate to url_ in its surrounding. Checked on two different machines.
The tooltip is displayed properly in Firefox and Edge.
Please note that Google Chrome is the browser that we recommend to opened AET reports with.

**Comment by annabudziszewska** [comment]
Tested and accepted
Version 3.3.1.SNAPSHOT
