### ISSUE TITLE
Failed to connect: Unable to create ProxyServer with ProxyManager: com.cognifide.aet.proxy.RestProxyManager

### ISSUE THREAD

**Issue by SapereaudeForest** [Cognifide/aet#485]
Hi 
I'm trying to run your tools but I have found an error during execution suite.xml sample. 

COMPARED: [success: 0, total: 0] ::: COLLECTED: [success: 0, total: 1]
[Collector-4] Couldn't process following url `http://www.cognifide.com` because of error: Failed to connect: Unable to create ProxyServer with ProxyManager: com.cognifide.aet.proxy.RestProxyManager

If I'm trying to run the test without proxy set I get no proxy error but get "Processing error occurred" visible in test report and the same info in execution log ('COMPARED: [success: 0, total: 0] ::: COLLECTED: [success: 0, total: 1]')

Can you please advise?

**Comment by Skejven** [comment]
Hi,
could you please tell:
- what version of AET you use
- how did you setup AET instance (Docker / Vagrant / Manual)
- attach your `suite.xml`

Currently there is too little information to say more.

**Comment by SapereaudeForest** [comment]
Hi @Skejven,
* what version of AET you use ( latest downloaded from repo ) 
* how did you setup AET instance (Docker / Vagrant / Manual) (same way how was described in your tutorial, however, I had an issue at the end which after using  _vagrant up_ command bellow notification pup-up:

> Vagrant was unable to mount VirtualBox shared folders. This is usually because the filesystem "vboxsf" is not available. This filesystem is made available via the VirtualBox Guest Additions and kernel module. Please verify that these guest additions are properly installed in the guest. This is not a bug in Vagrant and is usually caused by a faulty Vagrant box. For context, the command attempted was:
mount -t vboxsf -o uid=1000,gid=1000 keys /keys 

above issue was solved after _vagrant plugin repair_ and _vagrant provision_ 

I have same versions of vbox and others tools as described in manual.


* attach your suite.xml

default suite from your manual:
[https://github.com/Cognifide/aet/wiki/AETIn10Minutes](url)

Thanks for replying.

**Comment by Skejven** [comment]
Could you pleas ssh to your vagrant instance and check connectivity to http://www.cognifide.com (e.g. with curl or wget)? It looks like there is some problem with network.
If you fail to connect to the server, please try restarting the VM. If there will be still problem, please remove the vagrant instance and start it over.
You may also want to try https://github.com/Skejven/aet-docker if vagrant setup fails.
