### ISSUE TITLE
URL rerun doesn't work 

### ISSUE THREAD

**Issue by plutasnyy** [Cognifide/aet#487]
**Describe the bug**
Rerun url doesn't work

* Version used: `AET 3.2.0`

**To Reproduce**
1. Go to any URL
2. Click on rerun url button

You will see:
```
Status: URL rerun initialized

Progress: 0.00%
```
But it never change, I also see in "network" that URL in request looks good, every necessary parameter is added. In addition Rerun Test works correctly and URL is the same (without information about url to rerun obviously). The `currentRerunUrlEndpoint` in localStorage is `undefined`, in my opinion there could be a problem, but I am a bit confused because request is correct but after refresh I don't see information about the last rerun so probably it wasn't sent to process? It is strange, but I didn't investigate it more preciously.

**Expected behavior**
URL rerun works

**Comment by tostermis3** [comment]
Update: Error reproduced. At this moment after **rerun url** error in console appear:

```
angular.js:68 Uncaught Error: [$http:badreq] Http request configuration url must be a string.  Received: undefined
http://errors.angularjs.org/1.5.5/$http/badreq?p0=undefined
    at angular.js:68
    at $http (angular.js:11194)
    at Function.$http.(/anonymous function) [as get] (https://new-aet.cognifide.com/assets/libs/angular/angular.js:11439:18)
    at rerun.service.js:102
```

**Comment by annabudziszewska** [comment]
Tested and accepted
