### ISSUE TITLE
Problem with ActiveMQ

### ISSUE THREAD

**Issue by RdkLwg** [Cognifide/aet#492]
After some time of proper AET performance the tool starts to slow down significantly. It is so noticeable that makes AET unusable.
After various tests of restarting each part of AET we came up with a conclusion that restarting (destroying and recreating the kubernetes) ActiveMQ helps.
It's worth noticing that queues in ActiveMQ didn't look bad before restarting.

What also did not help:
- Clearing ActiveMQ queues - no change,
- Deleting ActiveMQ queues - this fixed issue for next 5 minutes, after that we experienced low performance again.

During the time when the issue appears we also observe:
- no issues with resources host-wise,
- no issues with resources container-wise.

* Version used: `AET 3.2.0`

Note that the problem is difficult to reproduce on demand and is not related to the number of concurrent test runs nor the infrastructure.

**Comment by wiiitek** [comment]
Nice bug! :) Could you tell more about *After some time of proper AET performance* ? Is it after days / weeks / months of normal work?

**Comment by karoldrazek** [comment]
Hello wiiitek,

it seems the problem with ActiveMQ came from misconfiguration of aet-docker.
After fixes from @Skejven we're all fine!
