### ISSUE TITLE
Implement a feature that will allow monitoring the size of responses for the given requests

### ISSUE THREAD

**Issue by krzysztofryk** [Cognifide/aet#501]
**Feature description**
Implement an additional Collector and Comparator that will allow one to sum the transferred data of the responses for the given/filtered requests. 

Adding this feature will allow monitoring the growth of the page size over time and to alert if the amount of the transferred data is bigger than an assumed threshold. 

**Example**
Consider an example where one does not configure the images renditions behaviour properly and effectively downloads the original version of these on mobile devices. It is relatively easy to overlook such an issue in the ongoing development without automating this test case. 

**Configurable elements**

- urlPattern in the Collector definition
- maxSize in the Comparator definition

**Report**
The additional tab should be displayed in the report

- the information about the overall amount of the transferred data
- the table of ordered requests (desc) and their attributes (URL as a link, Size in kilobytes)

**Comment by basia-wulnikowska** [comment]
Reports are working as expected
