### ISSUE TITLE
Unable to "Accept test case" after rerun - Undefined error

### ISSUE THREAD

**Issue by tostermis3** [Cognifide/aet#505]
I can't accept test case after test/suite rerun. `Undefined error` will appear.

1. Go to page/test with error.
2. Rerun test for page.
3. If page will have error, try to accept test case.
4. Save all changes.
5. `Error while saving metadata: [Undefined error]` will appear.

**Expected behavior**
Test case should be accepted and saved correctly.

<img width="331" alt="2019-04-15_11h12_04" src="https://user-images.githubusercontent.com/48392884/56120884-5f83ea00-5f6f-11e9-8700-7e97f93cbc59.png">

<img width="221" alt="2019-04-15_11h11_41" src="https://user-images.githubusercontent.com/48392884/56120892-614dad80-5f6f-11e9-9495-fe48315559ba.png">

**Comment by RdkLwg** [comment]
I cannot reproduce the problem (checked on the version 3.2.2). 
@tostermis3 can you verify if the issue still exists and if so provide some more details?

**Comment by tostermis3** [comment]
Sure, I tried to reproduce but on on ver 3.2.2 - and issue don't longer appear.
