### ISSUE TITLE
AET run failed on "element not found before timeout"

### ISSUE THREAD

**Issue by GrzegorzBednarski** [Cognifide/aet#551]
**Describe the bug**
When AET test will not found element before timeout - AET run will fail. 

* Version used: `AET 0.13.1 - docker version`

**To Reproduce**
1. Create test suite with click/wait-for-element-to-be-visible
2. Put any unobtainable selectors to click/wfetbv
3. Run test

**Expected behavior**
We should see error message, but tests should go forward. 

**Screenshots**
![2020-05-07_10h53_09](https://user-images.githubusercontent.com/22363159/81296065-a1e40180-9071-11ea-8a99-d257866d5199.png)
**Additional context**

**Comment by annabudziszewska** [comment]
Tested and accepted
version: 3.3.1.SNAPSHOT
