### ISSUE TITLE
401 from http://localhost:8181/system/console/bundles 

### ISSUE THREAD

**Issue by wonkas-factory** [Cognifide/aet#556]
**Describe the bug**
When building with vagrant up: 

==> default: * ruby_block[karaf-config-guard] action run
==> default: 
==> default: waiting for response code 401 from http://localhost:8181/system/console/bundles
==> default: incorrect response code. will try again in 5 seconds...
==> default: incorrect response code. will try again in 5 seconds...

Aborting since waiting for response code 401 from http://localhost:8181/system/console/bundles took more than 600 seconds

All the other services seem to be running fine Tomcat,ActiveMQ, MongoDB, Selenium Grid 

* Version used: `AET 3.3.0`, `Vagrant 2.2.9`, `Virtualbox 6.1.8r137981`, 'chefdk 4.7.73'

**To Reproduce**
From basic setup:
1. Added following to vagrant file to resolve dns
`v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]`
2. vagrant up
3. see outputs below

**Expected behavior**
No errors with vagrant up

**Screenshots**

**Additional context**
chef-stacktrace.out

> Generated at 2020-05-28 02:53:23 +0000
SystemExit: Aborting since waiting for response code 401 from http://localhost:8181/system/console/bundles took more than 600 seconds
/var/chef/cache/cookbooks/aet/libraries/helpers.rb:70:in `abort'
/var/chef/cache/cookbooks/aet/libraries/helpers.rb:70:in `abort_if_too_long'
/var/chef/cache/cookbooks/aet/libraries/helpers.rb:62:in `wait_for_response_code'
/var/chef/cache/cookbooks/aet/recipes/reboot.rb:46:in `block (2 levels) in from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/ruby_block.rb:31:in `block in action_run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:227:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/ruby_block.rb:30:in `action_run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:182:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource.rb:577:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:78:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:76:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:76:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:720:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:715:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:715:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:754:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application/client.rb:440:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application/solo.rb:224:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/bin/chef-solo:24:in `<top (required)>'
/usr/bin/chef-solo:75:in `load'
/usr/bin/chef-solo:75:in `<main>'

Vagrant output 
[provision.log](https://github.com/Cognifide/aet/files/4699089/provision.log)

**Comment by RdkLwg** [comment]
Hello @wonkas-factory, have tried a docker version? It is available at @Skejven' AET repo (https://github.com/Skejven/aet-docker).

**Comment by wonkas-factory** [comment]
Thanks this was a lot easier!

The docker swarm doesn't save db state of test results after docker swarm leave  --force? How do we save the results...

**Comment by PhilBug** [comment]
Docker swarm leave does not affect volumes therefore the results should not be lost. I suggest you open new issue on aet-docker repo and provide some details about your configuration and steps to reproduce.
