### ISSUE TITLE
clean configuration legacy for `useProxy` configuration

### ISSUE THREAD

**Issue by wiiitek** [Cognifide/aet#56]
Currently there is a possibility to configure web proxy with `"true"` value.
This makes the code unclear: see also the discussion for pull request at:
* https://github.com/Cognifide/aet/pull/53#discussion_r99493791

For resolution I like the second approach more:

> there will be only named type of a proxy (remove true as a possible value) after deprecating it first for e.g. 2 minor versions

(Alternative solution is to have the configuration value `"default"` be interpreted as `"rest"` proxy.)

Currently all suites using web proxy have it configured to `"rest"` as otherwise it doesn't work.

**Comment by Skejven** [comment]
As currently `true` does not work, i think we can get rid of it with no deprecated period.
