### ISSUE TITLE
Add missing tooltips in the report

### ISSUE THREAD

**Issue by RdkLwg** [Cognifide/aet#566]
There are some missing tooltips in the report:
- Go to next version,
- Go to previous version,
- Previous url,
- Next url.

**Comment by annabudziszewska** [comment]
The following tooltips are still missing:
Previous url,
Next url.

version: 3.3.1.SNAPSHOT
![image](https://user-images.githubusercontent.com/23029963/96136765-2d549f00-0efc-11eb-9541-fa59e962f140.png)

**Comment by annabudziszewska** [comment]
Tested and accepted
(during previous tests, app was only partially setted up)
version: 3.3.1.SNAPSHOT
