### ISSUE TITLE
Does screen with css selector work?

### ISSUE THREAD

**Issue by allankosciuszko** [Cognifide/aet#58]
AET version 2.0.2
Suite definition below seems to not work as expected.
It does't make screen of area by css selector, It makes always screen of whole page.
Does current AET version support this functionality ?

```
<?xml version="1.0" encoding="UTF-8" ?>

<suite name="test-suite" company="company" project="tests">
    <test name="google-homepage">

        <collect>
            <open/>
            <sleep duration="5000"/>
            <resolution width="800" height="600" />
            <screen name="logo" css="#hplogo"/>
        </collect>
        <compare>
            <screen collectorName="logo"> </screen>
        </compare>
        <urls>
            <url href="http:/google.com"/>
        </urls>
    </test>
</suite>
```

**Comment by subiron** [comment]
Hi @allankosciuszko 
Your suitedefinition seems to be fine, but 2.0.2 version wasn't released yet.
You can try mentioned feature by building AET on 2.0.2-rc2 tag.

If you're already using 2.0.2-rc2 please try to use other css selector (or try to use xpath)
also check our test suite definition for 
https://github.com/Cognifide/aet/blob/master/integration-tests/test-suite/partials/layout.xml

**Comment by subiron** [comment]
Hi @allankosciuszko version [2.0.2 was released](https://github.com/Cognifide/aet/releases/tag/2.0.2).
If yo want to check out new feature, please checkout master branch and follow our [10min guide](https://github.com/Cognifide/aet/wiki/AETIn10Minutes)
