### ISSUE TITLE
Duplicate of "Edit url note" button

### ISSUE THREAD

**Issue by Necromantian** [Cognifide/aet#585]
**Describe the bug**
Currently there are two "edit url note" buttons due to a failed merge on _master_ branch

**Screenshots**
![image](https://user-images.githubusercontent.com/38697940/96851706-9ab28380-1458-11eb-8591-117fa2a8509e.png)

**Additional context**
Code needs to be checked for any additional regressions.

**Comment by annabudziszewska** [comment]
Tested and accepted
