### ISSUE TITLE
Sidebar goes under AET logo while scrolling

### ISSUE THREAD

**Issue by jwadolowski** [Cognifide/aet#59]
Whenever I scroll the on the left hand side all the information displayed there go under AET logo

AET version: 2.0.1
Browser: Chrome 56.0.2924.87

![sidebar_issue](https://cloud.githubusercontent.com/assets/6334715/23158819/c606d368-f820-11e6-881e-c88c2900a2d4.png)

**Comment by RdkLwg** [comment]
This is the intended behavior. Clicking the AET logo allows the user to navigate to the suite level of a given report (a sort of equivalent of the 'home' button when compared to websites).

**Comment by jwadolowski** [comment]
Maybe that's just my opinion, but I wouldn't call it an intended behaviour :)

Please find additional screenshots below:

<img width="600" alt="aet_sidebar1" src="https://cloud.githubusercontent.com/assets/6334715/23168884/097fd95e-f84a-11e6-9b28-cec6a103580d.png">

<img width="624" alt="aet_sidebar2" src="https://cloud.githubusercontent.com/assets/6334715/23168621/0e77096a-f849-11e6-8ef2-eecff8c1823b.png">

It simply doesn't look right to me. The logo should be extended a bit to the right to cover the gap I marked on the 2nd screenshot - that's the simplest solution I can think of right now (I'm not a UI expert though).

**Comment by jwadolowski** [comment]
@RdkLwg could you reopen that please?

**Comment by mchrominski** [comment]
I agree with @jwadolowski. It's tricky to notice the issues but the flaws are quite obvious once you know what to look for.

**Comment by RdkLwg** [comment]
@jwadolowski as we arranged, there are two different issues - one is related to how it is displayed on Mac machines (issue with the logo that only partially covers links) and the other one related to urls that are cut whenever the user changes the size of the screen - raised at https://github.com/Cognifide/aet/issues/73.

**Comment by subiron** [comment]
tested and accepted
