### ISSUE TITLE
Request monitoring: total size of requests is not provided

### ISSUE THREAD

**Issue by annabudziszewska** [Cognifide/aet#599]
**Describe the bug**
The total size of requests for Request monitoring feature is not provided

* Version used: 3.3.1.SNAPSHOT

**To Reproduce**
1. Setup the request monitoring, as described in https://github.com/Cognifide/aet/pull/502
2. Check the report

**Expected behavior**
Total size of all defined requests is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/23029963/99402722-f0f4d400-28e9-11eb-9bea-68e1614f8041.png)

**Comment by mariuszkubis** [comment]
This bug is already fixed in https://github.com/Cognifide/aet/pull/597, please revalidate

**Comment by basia-wulnikowska** [comment]
This one is fixed. New bug with reports appeared and will be reported separately
