### ISSUE TITLE
Screen tabs in report app are not displayed correctly

### ISSUE THREAD

**Issue by jwadolowski** [Cognifide/aet#60]
There's 5 different screen in my project. In AET report webapp it translates to 8 tabs in total (5 screens + 3 static ones: `SOURCE W3C-HTML5`, `STATUS-CODES` and `JS-ERRORS`). When your screen resolution is not high enough it seems that tabs which don't fit into screen width get wrapped around. This makes the app unusable, i.e. it's quite hard to use `Show Mask` feature then. Here's a screenshot of that bug:

<img width="1438" alt="aet_tab_bug" src="https://cloud.githubusercontent.com/assets/6334715/23159330/a9497b5c-f822-11e6-88c1-025c54badf7d.png">

AET version: 2.0.1
Browser: Chrome 56.0.2924.87

**Comment by RdkLwg** [comment]
Hi Kuba, thanks for raising this issue. 
Yes, this feature needs improvements for sure. What you can do now to make use of tabs when there are 8 or more of them and at the same time to make use of other features that are partially covered by the misplaced tabs is change your screen size by zooming it out (CTRL and the key "-").

**Comment by subiron** [comment]
tested and accepted
