### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by SebaM** [Cognifide/aet#61]
Hi 

would you please consider to install more fonts to your OS? Especially those like Chinese or Arabic. Currently, it's been missing those and even the page is looking good at my local web browser
 at EAT it looks as on the screen:
<img width="309" alt="screen shot 2017-02-22 at 12 06 41" src="https://cloud.githubusercontent.com/assets/2609426/23209079/f014c962-f8f7-11e6-9e53-f6bb97b31ed4.png">

**Comment by subiron** [comment]
Hi @SebaM 
I'm not  sure if I fully understand your question...
Can't you just use webfonts on your site?
e.g.  see https://www.w3schools.com/css/css3_fonts.asp

Think of AET tool as an enduser of your page - do you also want to sugest that they need to install system fonts on thiers OSes ? ;)
But if this is not an option in your case then try to add fonts on your instance by yourself 
if you're using AET on linux place desired fonts inside /usr/share/fonts or /usr/share/fonts/truetype directories, AETs FireFox should use them.
Let me know if this answers your question
Br

**Comment by SebaM** [comment]
Yes, exactly my suggestion was enriched default OS by adding new languages support just in case your tested page was not in English. 

Eg. it worked for us:
 yum groupinstall chinese-support
 yum groupinstall arabic-support

**Comment by Skejven** [comment]
This question will be listed in FAQ: #81 . Thanks @SebaM and @subiron for sharing.
