### ISSUE TITLE
Add ability to wait for some element to appear on the page

### ISSUE THREAD

**Issue by tommix1987** [Cognifide/aet#62]
Current implementation of wait for page loaded modifier is not sufficent for pages containing dynamic web applications, especially when there is some delay of page load (our client servers are in US, thus the page load time takes a bit)
The scenario is as follows:
1. Page loads with most of the stuff on the page
2. Dynamic application starts running, contacts few backend services, etc.
3. Once the dynamic data comes back page gets modified

What we've seen was that wait for page load was stopping at random moments during dynamic application load. To overcome that we had to add a whole bunch of sleeps here and there, which made our tests run for a very long time.

I would like to suggest a new modifier, where:
- You will be able to specify xpath to element that the modifier should wait for
- Timeout (optional - default value of 5? seconds)
- Treshold between checks (optional - default value o 500ms?)

**Comment by tommix1987** [comment]
What do you think @wiiitek @Skejven ?

**Comment by subiron** [comment]
It seems to be a very good idea - an alternative to existing 'WaitForPageLoadedModifier'.
Remember that there are some practical limitations on for how long we want to wait for a single page to load. There always must be some kind upper limit to prevent blocking of a queue.
Also check WaitForPageLoadedModifier implementation  @ 
https://github.com/Cognifide/aet/blob/master/core/jobs/src/main/java/com/cognifide/aet/job/common/modifiers/waitforpageloaded/WaitForPageLoadedModifier.java

Maybe try to fix root of the problem and not patch the consequences of it - I mean waiting over 10s for page to load- Maybe setting up  AETs closer to the end servers will do the trick.

**Comment by Skejven** [comment]
@tommix1987 Thank you for the proposition.
It is a very good idea. We even had something similar in mind earlier.
The element you described can be treated as `wait-until-event`. Maybe you could consider another option (let us know if this could help your case) - `wait-until-xhr-finished` which basic idea is:
`Check if new XHR happened. If yes, wait one more second. Otherwise, finish waiting`.

**Comment by wiiitek** [comment]
@tommix1987 if you need it and want to write some code: go for it.
Some ideas you may consider:

1. specify element not only by xpath but also CSS selector (to be in sync with [click](https://github.com/Cognifide/aet/wiki/ClickModifier) and [hide](https://github.com/Cognifide/aet/wiki/HideModifier) modifier) 
2. optional config for number of elements to wait for? (i.e. if someone needs to wait for more than one element with given selector) ?

**Comment by tommix1987** [comment]
Hi,
Both ideas look really good I will  include them.
Best regards
TS

23.02.2017 10:02 PM "wiiitek" <notifications@github.com> napisał(a):

**Comment by tommix1987** [comment]
@Skejven For me waiting for xhr would not be enough - I have asynchronous Angular application on page, there might be various things happening with markup after XHR call finished, thus I would rather want to observe markup - since I'm interested in the final markup that gets rendered.

**Comment by tommix1987** [comment]
@wiiitek Looking at the current code for simplicity I think I will start with waiting for one element for now, secondly I think I will leave the "sleep" before checks non-configurable for now - it's 500 miliseconds right now which seems good enough. 
After reviewing the codbase my Modifier will be very similar to click modifier - it will simply wait for element to become visible instead of trying to click it ;)

**Comment by wiiitek** [comment]
Ok :)

**Comment by Skejven** [comment]
Added in #166
