### ISSUE TITLE
Support Java 8 source format?

### ISSUE THREAD

**Issue by toniedzwiedz** [Cognifide/aet#65]
During one of the code reviews, I noticed that the [sources of AET are written in Java 7](https://github.com/Cognifide/aet/blob/master/pom.xml#L115) (this is used later on in the [Maven Compiler plugin config](https://github.com/Cognifide/aet/blob/master/pom.xml#L802))

Is there a reason the project hasn't migrated to Java 8?

It seems there's already some requirement to build (or use, I'm not sure )the project using Java 8 that has something to do with Bobcat.

https://github.com/Cognifide/aet/blob/master/pom.xml#L135

**Comment by Skejven** [comment]
Hi @toniedzwiedz , thank you for the question.

AET uses [Apache Karaf 2.3.9](https://github.com/Cognifide/aet/wiki/SystemComponents#third-party-software-used-by-system) which unfortunately does not support Java 8:

http://karaf.apache.org/download.html

We tried some (long) time ago to migrate to higher version of Karaf which failed.
Currently there is another solution on the horizon during which we want to finally upgrade to JDK 8: #7
