### ISSUE TITLE
Support for regular expressions in all reasonable parameters of Filters and Modifiers

### ISSUE THREAD

**Issue by chutch** [Cognifide/aet#67]
Sometimes it is hard to target specific set of W3C errors with the same type, because they differ, they are parametrized.
At the same time, using prefix seems to be too broad.
Please provide possibility to use regular expressions.

**Comment by subiron** [comment]
Hi @chutch 
Thank you very much for your contribution.
what`s more, the same type of improvement can be applied in other DataModifiers and DataFilters.
...I'm on it

**Comment by subiron** [comment]
work started in branch ZGCQ-8135
(due to hotfix for an internal project)

**Comment by wiiitek** [comment]
Let's start with adding Regular expressions for following filters:

* `accessibility-filter` for error pattern
* `js-errors-filter` for error pattern
* `w3c-filter` for message pattern

**Comment by RdkLwg** [comment]
I would also add regular expressions allowing to filter out warnings - there are some cases when the user may need warnings but still going through a long list each time can be a pain when a team is blocked and cannot fix a given warning.

**Comment by wiiitek** [comment]
@RdkLwg , filtering for accessibility will also work for warnings: it is possible to exclude warnings by regular expressions.
