### ISSUE TITLE
Links get cut when the user changes the screen size

### ISSUE THREAD

**Issue by RdkLwg** [Cognifide/aet#73]
urls get cut when the user expands the list of browsers and changes the size of the screen.

To reproduce:
1. Open your chrome browser in a full-screen mode
2. Open any report with a number of  long urls
3. Expand the list
4. Note that long urls are shortened as intended
5. Collapse the list
6. Change the size of the screen
7. Set the full screen again
8. Expand a list of urls
9. Note that some urls got cut

*Actual result:* urls get cut when the user expands the list of browsers and changes the size of the screen.

![urls-issues](https://cloud.githubusercontent.com/assets/22235601/23656716/1e9d75e8-033b-11e7-9ff9-349f65a119d3.png)

*Expected result:* urls do not get cut when the user expands the list of browsers and changes the size of the screen.

**Comment by agul89** [comment]
This issue is dependant on changes in https://github.com/Cognifide/aet/pull/74, so will be resolved on the same branch.

**Comment by subiron** [comment]
tested and accepted
