### ISSUE TITLE
Under certain circumstances AET can collect wrong page content

### ISSUE THREAD

**Issue by jwadolowski** [Cognifide/aet#75]
Hi,

during one of AET run completely wrong page was collected and presented in the report. Here's a screenshot that presents the problem:

![aet_odd_result](https://cloud.githubusercontent.com/assets/6334715/23680278/efc89e32-038a-11e7-9d20-4bf0d2618f4b.png)

I had to blur a lot above, but it's quite obvious that these 2 pages are completely different. Surprisingly, subsequent AET run produced expected result - the appropriate page was collected and compared with the pattern. 

It definitely wasn't an application issue, as collected content has never been present under that path (it was one of other paths we defined in our test suite).

I had a quick chat with @Skejven about this problem and he mentioned that it can be side effect of multiple `<open/>` elements in our XML file. Here's a snippet of its current shape:

```xml
<collect>
    <resolution width="1920" height="1024"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="extralarge"/>
    <resolution width="1250" height="900"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="large"/>
    <resolution width="1150" height="900"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="medium"/>
    <resolution width="769" height="900"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="medium2"/>
    <resolution width="400" height="900"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="small"/>
    <source/>
    <status-codes/>
    <js-errors/>
</collect>
```

What could be a possible root cause? How can we overcome that problem?

It happened just once so far (1 out of hundreds collections), so unfortunately I don't have exact reproduction steps. I can consider that as an incident, but since it took place I'd like to get some insights and see what can be done to prevent similar situations in the future.

Cheers,
Kuba

**Comment by RdkLwg** [comment]
Because of the great number of animations in one of my projects I've made use of the same configuration (i.e. multiple <open/>). I haven't come across such an issue for over 5 months. It looks like the issue you came across happened for the screen size collected as the first one, which is also kind of weird (I would suspect to get this problem rather after using <open/> for the second or third time.

**Comment by jwadolowski** [comment]
Thank you for your response Radek.

I can see 3 possible scenarios here:
* current one
```xml
<collect>
    <resolution width="1920" height="1024"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="extralarge"/>
    <resolution width="1250" height="900"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="large"/>
    <resolution width="1150" height="900"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="medium"/>
    <resolution width="769" height="900"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="medium2"/>
    <resolution width="400" height="900"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="small"/>
    <source/>
    <status-codes/>
    <js-errors/>
</collect>
```
* alternatively we reduce number of `<open/>` elements to 1, so it'll look like this
```xml
<collect>
    <resolution width="1920" height="1024"/>
    <sleep duration="4000"/>
    <screen name="extralarge"/>
    <resolution width="1250" height="900"/>
    <sleep duration="4000"/>
    <screen name="large"/>
    <resolution width="1150" height="900"/>
    <sleep duration="4000"/>
    <screen name="medium"/>
    <resolution width="769" height="900"/>
    <sleep duration="4000"/>
    <screen name="medium2"/>
    <resolution width="400" height="900"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="small"/>
    <source/>
    <status-codes/>
    <js-errors/>
</collect>
```
I'm not sure if that's the right way to go and what side effects it may cause
* introduce multiple `<collect>` blocks - one for each resolution
```xml
<collect>
    <resolution width="1920" height="1024"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="extralarge"/>
    <source/>
    <status-codes/>
    <js-errors/>
</collect>
<urls>
    <url href="/path/to/page1.html"/>
    <url href="/path/to/page2.html"/>
    <url href="/path/to/page3.html"/>
</urls>
...
<collect>
    <resolution width="1250" height="900"/>
    <open/>
    <sleep duration="4000"/>
    <screen name="large"/>
    <source/>
    <status-codes/>
    <js-errors/>
</collect>
<urls>
    <url href="/path/to/page1.html"/>
    <url href="/path/to/page2.html"/>
    <url href="/path/to/page3.html"/>
</urls>
```

The obvious downside of this approach is massive duplication, as we have to repeat the same set of URLs for each resolution. 

Could you take a look at above and advise which approach is the correct one? What are the pros and cons of each of them?

Thanks,
Kuba

**Comment by wiiitek** [comment]
It should be enough to open a page once (provided that responsive design is in place):

```xml
<collect>
    <open/>

    <resolution width="1920" height="1024"/>
    <sleep duration="4000"/>
    <screen name="extralarge"/>

    <resolution width="1250" height="900"/>
    <sleep duration="4000"/>
    <screen name="large"/>

    <resolution width="1150" height="900"/>
    <sleep duration="4000"/>
    <screen name="medium"/>

    <resolution width="769" height="900"/>
    <sleep duration="4000"/>
    <screen name="medium2"/>

    <resolution width="400" height="900"/>
    <sleep duration="4000"/>
    <screen name="small"/>

    <source/>
    <status-codes/>
    <js-errors/>
</collect>
```

**Comment by jwadolowski** [comment]
I haven't experienced similar issues since AET 3.x upgrade.

**Comment by RdkLwg** [comment]
thank you @jwadolowski for your confirmation.
