### ISSUE TITLE
Selenium Grid

### ISSUE THREAD

**Issue by Skejven** [Cognifide/aet#8]
Idea of this epic is to get rid of current strong connection between AET core and Firefox browser. Instead of using selenium driver. AET should use [Selenium Grid](https://github.com/SeleniumHQ/selenium/wiki/Grid2) to use remote browser.
This epic will provide new possibilities:
- separate AET infrastructure and browser (no selenium/webdriver dependency),
- support wider range of browsers.

**Comment by tommix1987** [comment]
This sounds really interesting and in my opinion would be a real gamechanger!

**Comment by KrzysztofZalasa** [comment]
Really good idea. It simplifies environment setup and makes possible to reuse of existing infrastructure prepared for functional tests instead of creating dedicated nodes for AET.

**Comment by Skejven** [comment]
Selenium Grid is already available with AET
