### ISSUE TITLE
Report - unable to save notes(comments) on case level

### ISSUE THREAD

**Issue by subiron** [Cognifide/aet#87]
Steps to reproduce:
- open  any AET report
- click on any test
- click on any url
- click on 'notes' icon on case level
- fill form and clic "updata"
- click "save all changes"
- reload page

Expected :
- entered comment is saved, and visible
Actual:
- comment is not saved

Also there are no functional test coverage for comments feature
We should add CRUD scenarios for each nesting level (suite, tests, case) in sanity-functional module.

**Comment by subiron** [comment]
please note that this bug also occurs in v 2.0.1

**Comment by RdkLwg** [comment]
This issue affects the version 3.0.x

**Comment by tkaik** [comment]
Fixed in https://github.com/Cognifide/aet/pull/363
